# Generated by Django 4.2.26 on 2025-11-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorresult',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('cumple', 'Cumple'), ('incumple', 'Incumple'), ('no_capturado', 'No capturado')], default='pendiente', max_length=20),
        ),
    ]
